apiVersion: v1
kind: Service
metadata:
  namespace: helpdesk
  name: helpdesk-api-svc
spec:
  selector:
    app: helpdesk-api
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30010
      protocol: TCP