apiVersion: v1
kind: Service
metadata:
  name: postgres-service-cluster
  namespace: helpdesk
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
