apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: helpdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.8-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: helpdeskdb
      restartPolicy: Always
