apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: helpdesk
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30009
      targetPort: 5432
      protocol: TCP
